version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000  # Add API URL for frontend
      - WATCHPACK_POLLING=true              # Enable hot reload in Docker
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
